# Site settings
title: zironycho's home
email: zironycho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zironycho.github.io/" # the base hostname & protocol for your site

twitter_username: zironycho
github_username: zironycho

# Build settings
markdown: kramdown
exclude:
  - bundle
